### PR TITLE
add tsuki!

### PR DESCRIPTION
**Pull request by tsuuki**
see title

### CODE REVIEW

**Comment by tsuuki** [comment]
i would implement a "description" box but i am not sure if you want that so i will just suggest it here instead

**Comment by troke12** [comment]
> i would implement a "description" box but i am not sure if you want that so i will just suggest it here instead

sure why not, feel free to implement here!

**Comment by tsuuki** [comment]
i will do that later, can you merge this for the meantime?

**Comment by troke12** [comment]
alright merged!

**Comment by tsuuki** [comment]
cheers mate

**Pull request merged**
